server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.129.12.55:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 60000
    validationQuery: SELECT 1 FROM DUAL
mybatis-plus:
  type-aliases-package: cn.cyf.*.entity
  mapper-locations: classpath:mapper/*.xml

